### PR TITLE
Prepare for release 2.5.0

### PR DESCRIPTION
**Pull request by g-andrade**

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
Would it be desirable to not self-accept and merge pull requests as a good pratice? Otherwise there's really no difference between this and "pushing to master" directly, except for the unwarranted noise.

**Comment by g-andrade** [comment]
I thought that 1) you were on vacation and 2) no one else would care enough. 

Therefore either I would have to either:
- A) wait for you to return from your vacation (as it turns out, a fictional one) and freeze a bunch of work for a change that's _very_ difficult to get wrong (and therefore whose review is of minute value), or
- B) go ahead with the release (which is what I did.)

**Comment by g-andrade** [comment]
>  except for the unwarranted noise.

I thought that this "noise" was desirable (albeit I don't care of it myself) in that it's better to have some information than to have none.

**Comment by paulo-ferraz-oliveira** [comment]
I'm on vacation from work, not GitHub, where I use my personal time.

**Comment by g-andrade** [comment]
> I'm on vacation from work, not GitHub, where I use my personal time.

Ah! I do it on a per-repo basis (including the email account where notifications end up.) This would never have occurred to me... 😄

**Comment by g-andrade** [comment]
Nevertheless, I stand by my decision process, I just got the facts wrong.

**Comment by paulo-ferraz-oliveira** [comment]
I use GitHub notifications.

**Comment by paulo-ferraz-oliveira** [comment]
Well, forget what I said. I'm not the only owner of these repo.s, and if nobody else's interested in these things I really won't care by myself either. It's just confusing that sometimes there is a process and sometimes there isn't one.

**Comment by g-andrade** [comment]
>  It's just confusing that sometimes there is a process and sometimes there isn't one.

We're talking about a one-line change in auxiliary materials which would have to wait for almost week (if you had indeed been unavailable.)

Not all changes are equal in impact, consequence or range. Come on. I'm trying to be reasonable, here. Rules can't cover every possible situation, and that's why we bend them when needed.

**Pull request merged**
