### PR TITLE
Actually run on different Erlang versions

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**

### CODE REVIEW

**Comment by g-andrade** [comment]
CI is still failing in OTP 19.3, due to typing issues.

**Comment by paulo-ferraz-oliveira** [comment]
> CI is still failing in OTP 19.3, due to typing issues.

Yeah, I saw this. I guess these weren't exported in OTP 19.3 yet. Will just go the old MACRO-way of living, if that's the case.

**Comment by paulo-ferraz-oliveira** [comment]
This is failing because of `tls_certificate_check` using `public_key` types that aren't exported. I'm going to comment `unknown` until we decide to move up an OTP version.

**Comment by g-andrade** [comment]
> This is failing because of tls_certificate_check using public_key types that aren't exported. 

Why wouldn't `make check`s for `tls_certificate_check` point this out? This crap keeps happening to me... you need to lend me your Dialyzer someday. Mine doesn't work.

**Comment by paulo-ferraz-oliveira** [comment]
> Why wouldn't `make check`s for `tls_certificate_check` point this out? This crap keeps happening to me... you need to lend me your Dialyzer someday. Mine doesn't work.

We're potentially not using it over the same Erlang versions (?)

**Comment by g-andrade** [comment]
> We're potentially not using it over the same Erlang versions (?)

The issue has been happening to me since time immemorial. It's past any logical explanation at this point, only supernatural factors can account for it now.

**Comment by paulo-ferraz-oliveira** [comment]
Tests seem to be up again. The basic problem with connectivity was running a Docker container for Erlang and a Redis service inside it. I'm now running a Ubuntu container (with no Erlang container), Redis as a service and Erlang as an installed element. It performs as expected...

**Review by g-andrade — APPROVED** [review]

**Pull request merged**
